services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - internal
    depends_on:
      - db

  db:
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    volumes:
      - ./data/database:/var/lib/postgresql/data
    networks:
      - internal

networks:
  internal:
    external: false