on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: Backend CI

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.24.1'

      - name: Check gofmt
        run: |
          unformatted=$(gofmt -l .)
          if [ -n "$unformatted" ]; then
            echo "These files are not formatted:"
            echo "$unformatted"
            exit 1
          fi
      
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.24.1'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0